"""Write the brain's daily reasoning into Obsidian — the thinking, not just the result.

This is the brain's journal. It records what the system believed today, what it
tested, what changed since yesterday, and which constraints actually shaped the
paper. A reader should be able to open one note and reconstruct why that day's
paper looks the way it does.

Numbers come from backtest artefacts in out/. None is generated by a model.
"""

from __future__ import annotations

import argparse
import json
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "out"
VAULT = Path.home() / "Documents" / "Obsidian" / "Project Yaga" / "SSC CGL"


def read(name: str) -> dict | list:
    p = OUT / name
    try:
        return json.loads(p.read_text()) if p.exists() else {}
    except Exception:
        return {}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=date.today().isoformat())
    a = ap.parse_args()
    day = a.date

    reg = read("setter_register.json").get("tested", {})
    setter = read("setter_model.json")
    temporal = read("temporal.json")
    ql = read("question_level_backtest.json")
    lb = read("layer_backtest.json")
    gz = read("ga_zones_2026.json")
    brain = read("brain_last.json")
    ca = read("current_affairs.json").get("items", [])
    ledger = read("adaptive_state.json")
    cv = read("ga_consensus_validation.json")

    daily = VAULT / "Daily Predictions"
    daily.mkdir(parents=True, exist_ok=True)

    L = [f"# Brain journal — {day}", "",
         "> What the system believed today, what it tested, and which",
         "> constraints shaped the paper. Auto-written by `src/obsidian_memory.py`.",
         "", "---", "", "## 1. The model of the setting team", ""]

    conf = {k: v for k, v in reg.items() if v.get("verdict") == "CONFIRMED"}
    rej = {k: v for k, v in reg.items() if v.get("verdict") == "REJECTED"}

    L.append("### Active constraints — these shaped today's paper")
    L.append("")
    if conf:
        for k, v in conf.items():
            L.append(f"- **{k}** — {v.get('claim','')}")
            L.append(f"  - evidence: `{json.dumps(v.get('evidence',{}))}`")
            if v.get("reading"):
                L.append(f"  - reading: {v['reading']}")
    else:
        L.append("_None confirmed._")
    L += ["", "### Explicitly NOT modelled — tested and rejected", ""]
    for k, v in rej.items():
        L.append(f"- **{k}** — {v.get('claim','')}")
        if v.get("reading"):
            L.append(f"  - {v['reading']}")
    L.append("")
    L.append("Rejections matter as much as confirmations: each one stops the")
    L.append("system modelling something the corpus says is not there.")

    # ---- process model -------------------------------------------------
    if setter:
        L += ["", "## 2. How the team composes a paper", ""]
        for h, label in (("H1", "day-level blueprint"),
                         ("H2", "shift position"),
                         ("H3", "frame reuse across shifts")):
            r = setter.get(h)
            if r:
                L.append(f"- **{h} {label}** — {r.get('verdict','')}")
        L += ["", "> For each exam day the team fixes a topic blueprint, then writes",
              "> three independent fresh question sets to it. Shift order carries",
              "> no signal.", ""]

    # ---- what is predictable -------------------------------------------
    L += ["## 3. What is predictable, measured", "",
          "| Layer | Measured |", "|---|---|"]
    res = gz.get("blind_result", {}) if isinstance(gz, dict) else {}
    if res:
        L.append(f"| GA knowledge zones | **{res.get('direct_plus_partial_pct',0):.1f}%** "
                 f"covered-or-adjacent on {res.get('n','?')} held-out 2025 Qs |")
    if lb.get("L3_topic_ranking"):
        L.append(f"| Topic ranking (top-10) | {100*lb['L3_topic_ranking'].get('top_10',0):.1f}% |")
    if lb.get("L2_topic_counts"):
        L.append(f"| Topic counts | {100*lb['L2_topic_counts'].get('skill',0):.1f}% skill vs uniform |")
    if ql:
        L.append(f"| Specific questions | **{100*ql.get('realised',{}).get('implied_sa_rate',0):.2f}%** "
                 f"(ceiling {100*ql.get('ceiling',{}).get('near_dup_080',0):.2f}%) |")
    if temporal:
        L += ["", f"**Drift:** {temporal.get('drift_verdict','—')}",
              "", f"**Regime change:** {temporal.get('accel_verdict','—')}"]

    # ---- today's inputs -------------------------------------------------
    L += ["", "## 4. What came in today", ""]
    if ca:
        from collections import Counter
        zc = Counter(i.get("zone") for i in ca)
        L.append(f"- current-affairs items held: **{len(ca)}** across {len(zc)} zones")
        L.append("")
        L.append("| Zone | Items |")
        L.append("|---|---|")
        for z, n in zc.most_common(8):
            L.append(f"| {z} | {n} |")
        L += ["", "Most recent facts:", ""]
        for i in ca[:6]:
            L.append(f"- _{i.get('zone')}_ — {i.get('headline','')[:150]}")
    else:
        L.append("_No current-affairs items._")

    # ---- ops ------------------------------------------------------------
    L += ["", "## 5. Operational state", ""]
    obs = brain.get("observed", {}) if isinstance(brain, dict) else {}
    if obs.get("runway"):
        L.append("| Section | Days of unrepeated papers |")
        L.append("|---|---|")
        for k, v in sorted(obs["runway"].items(), key=lambda kv: kv[1]):
            L.append(f"| {k} | {v} |")
    for d in (brain.get("decided", []) if isinstance(brain, dict) else []):
        L.append(f"- decision: **{d.get('action')}** — {d.get('why','')}")
    if ledger:
        L.append(f"- questions served to date: {len(ledger.get('served', {}))} "
                 f"across {len(ledger.get('papers', {}))} papers (never repeated)")
    if cv:
        g = cv.get("gated", {})
        L.append(f"- GA model consensus: {100*g.get('accuracy',0):.1f}% accurate "
                 f"at {100*g.get('coverage',0):.0f}% coverage")

    # ---- diff vs yesterday ---------------------------------------------
    prev = daily / f"{(date.fromisoformat(day) - timedelta(days=1)).isoformat()}.md"
    L += ["", "## 6. Change since yesterday", ""]
    if prev.exists():
        old = prev.read_text()
        moved = []
        for k, v in reg.items():
            tag = f"**{k}**"
            if tag in old:
                was_conf = f"- {tag}" in old.split("### Explicitly NOT")[0]
                now_conf = v.get("verdict") == "CONFIRMED"
                if was_conf != now_conf:
                    moved.append(f"- **{k}** changed verdict -> {v.get('verdict')}")
        L += moved or ["- No constraint changed verdict."]
    else:
        L.append("- No prior journal; this is the baseline.")

    L += ["", "---", "",
          f"[[SSC CGL]] · [[Setter Brain — Hypothesis Register]] · "
          f"[[Temporal Analysis — Drift Is A Measurement Artefact]] · "
          f"[[Setter Process Model]]", ""]

    note = daily / f"{day}.md"
    note.write_text("\n".join(L))
    print(f"obsidian -> {note}")


if __name__ == "__main__":
    main()
